.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. cuckoocoin_qt test_cuckoocoin_qt
clean: FORCE
	$(MAKE) -C .. cuckoocoin_qt_clean test_cuckoocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_cuckoocoin_qt_check
cuckoocoin-qt cuckoocoin-qt.exe: FORCE
	 $(MAKE) -C .. cuckoocoin_qt
