#ifndef CUCKOOCOIN_CHAINPARAMSSEEDS_H
#define CUCKOOCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the cuckoocoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x58,0x56,0xba,0x9e}, 27333}
};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x58,0x56,0xba,0x9e}, 37333}
};
#endif // CUCKOOCOIN_CHAINPARAMSSEEDS_H
