#!/bin/bash

# This is a thin wrapper around cuckoocoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using cuckoocoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_CUCKOOCOIND

# Grab the value of $REAL_CUCKOOCOINCLI which may be cuckoocoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_CUCKOOCOINCLI}" "$@" | sed 's/\r//'
